<?php

/**
 * Do not edit this file as it contains important fallback-configurations.
 * If you wish to edit the TodoMonkey configuration file, please
 * edit "noteplex_settings.php".
 */
return array(
    'System-language' => 'en-gb',
    'System-timezone' => 'Europe/London',
    'System-page_size' => '10',
    'System-theme' => 'todomonkey_purple.css',
    'System-header_code' => '',
    'System-captcha_publicKey' => '',
    'System-captcha_privateKey' => '',
    'System-public_todos_enabled' => '0',
    'System-uploads_enabled' => '0',
    'System-uploads_quota' => '5',
    'System-uploads_filesize' => '1',
    'System-uploads_extensions' => 'jpg,jpeg,gif,png,txt',
    'Ads-sub_categories_active' => '0',
    'Ads-sub_categories_height' => '135',
    'Ads-sub_categories_code' => '',
    'Ads-sub_todo_active' => '0',
    'Ads-sub_todo_height' => '70',
    'Ads-sub_todo_code' => '',
    'Layout-logo' => '<span class="link"><i class="icon-edit"></i> TodoMonkey</span>',
    'Layout-menu' => '',
    'Layout-footer_left' => 'Copyright © 2013 ClientEngage',
    'Layout-footer_center' => 'Powered by <a href="http://www.clientengage.com" target="_blank"><b>Client</b><em>Engage</em></a>',
    'Layout-footer_right' => '<a href="#">Terms & Conditions</a> | <a href="#">Privacy Policy</a> | <a href="#">About</a>',
    'Email-email' => 'admin@example.com',
    'Email-sender' => 'TodoMonkey Admin',
    'Email-transport' => 'mail',
    'Email-host' => '',
    'Email-port' => '',
    'Email-username' => '',
    'Email-password' => '',
);
